name: zonta
description: Zonta mobile application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.3.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  archive: ^3.6.1
  win32: ^5.5.3
  get: ^4.6.6
  awesome_snackbar_content: ^0.1.4
  webview_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/array_embed.html
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
